// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9jRBsoSq-NAMAKkKXkQZihEhgfFvRMNc',
    appId: '1:829473099878:web:6adfd86f6bdd3dd8209da7',
    messagingSenderId: '829473099878',
    projectId: 'flutter-chat-app-8a0be',
    authDomain: 'flutter-chat-app-8a0be.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8a0be.firebasestorage.app',
    measurementId: 'G-TVGJNCFSYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAylQ2WvsN5x5ObYL1YhfiedJXOLNWJ6bQ',
    appId: '1:829473099878:android:af00751e23e40de7209da7',
    messagingSenderId: '829473099878',
    projectId: 'flutter-chat-app-8a0be',
    storageBucket: 'flutter-chat-app-8a0be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJ7WA9gu_1l_hl_1do-PDBHZBossPr9M',
    appId: '1:829473099878:ios:6426b5b068a49cad209da7',
    messagingSenderId: '829473099878',
    projectId: 'flutter-chat-app-8a0be',
    storageBucket: 'flutter-chat-app-8a0be.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfJ7WA9gu_1l_hl_1do-PDBHZBossPr9M',
    appId: '1:829473099878:ios:6426b5b068a49cad209da7',
    messagingSenderId: '829473099878',
    projectId: 'flutter-chat-app-8a0be',
    storageBucket: 'flutter-chat-app-8a0be.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9jRBsoSq-NAMAKkKXkQZihEhgfFvRMNc',
    appId: '1:829473099878:web:57cdd6550d6d365a209da7',
    messagingSenderId: '829473099878',
    projectId: 'flutter-chat-app-8a0be',
    authDomain: 'flutter-chat-app-8a0be.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8a0be.firebasestorage.app',
    measurementId: 'G-W593X1HFKR',
  );

}